services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=yuuc
            - POSTGRES_DB=conference
        ports:
            - 15432:5432
        command: ["postgres", "-c", "listen_addresses=*"]
